config/routes.rb
LeaveCalendar::Application.routes.draw do

  resources :organizations
  resources :leave_infos
  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  
  match "account" => "account#index"
  resources :requests do
    get "cancellation"
    put "cancel"
    get "approving"
    put "approve"
    get "rejecting"
    put "reject"
  end

  match "admin", to: "admin#index"
  namespace :admin do
    resources :users
  end
    
  match '', to: 'welcome#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  

   root :to => 'welcome#index'
   

end

app/views/admin/index.html.erb
<div class="horizontal_list">
  <ul>    
    <li><%= link_to 'New User', new_admin_user_path, :class => "btn btn-primary" %></li>
  </ul>
</div>
<h1>Pending requests</h1>

  <table class = "table table-striped">
    <tr>
      <th>User name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Type</th>
      <th>Comment</th>
      <th>Status</th>
      <th></th>
      <th></th>
    </tr>

  <% @requests.each do |request| %>
    <% if request.status == "Pending" %>
      <tr>
        <td><%= request.user.name %></td>
        <td><%= request.start_date.to_date %></td>
        <td><%= request.end_date.to_date %></td>
        <td><%= request.type %></td>
        <td><%= request.comment %></td>
        <td><%= request.status %></td>
        <td><%= modal_me_to 'Approve', request_approving_path(request), {:class=>'btn btn-primary'}, "Approving Request" %></td>
        <td><%= modal_me_to 'Reject', request_rejecting_path(request),  {:class=>'btn btn-danger'}, "Rejecting Request", confirm: 'Are you sure?' %></td>
      </tr>
    <% end %>
  <% end %>

</table>