config/routes.rb
LeaveCalendar::Application.routes.draw do

  resources :organizations
  resources :leave_infos
  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  
  match "account" => "account#index"
  resources :requests do
    get "cancellation"
    put "cancel"
    get "approving"
    put "approve"
    get "rejecting"
    put "reject"
  end

  match "admin", to: "admin#index"
  namespace :admin do
    resources :users
  end
    
  match '', to: 'welcome#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  

   root :to => 'welcome#index'
   

end

app/models/request.rb
class Request
  include Mongoid::Document
  field :start_date, :type => DateTime
  field :end_date, :type => DateTime
  field :type, :type => String
  field :comment, :type => String
  field :status, :type => String
  
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :type, :presence => true
  validates :comment, :presence => true
  validates :status, :presence => true
  
  validate :start_or_end_date_cannot_be_in_the_past
  validate :cannot_be_same_date
  validate :enough_leave_to_take_or_not
  
  belongs_to :organization
  belongs_to :user
  attr_accessible :cancel
  
  def start_or_end_date_cannot_be_in_the_past
    if !start_date.blank? and (start_date < Date.today or end_date < Date.today )
      errors.add(:start_date, "Can't be in the past")
      errors.add(:end_date, "Can't be in the past")
    end
  end
    
  def cannot_be_same_date
    if !start_date.blank? and start_date == end_date
      errors.add(:start_date, "Can't be same day")
      errors.add(:end_date, "Can't be same day")
    end
  end
  
  def enough_leave_to_take_or_not
    user_remaining_leave = self.user.leave_infos.where(:leave_type => self.type).all.first.remaining_leave
    if !start_date.blank? and (end_date-start_date) > user_remaining_leave
      errors.add(:start_date, "You do not have enough remaining leave")
      errors.add(:end_date, "You do not have enough remaining leave")
    end
  end
    
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :load_organization
  before_filter :authenticate_user!
  
  def index
    @requests = current_user.requests.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = current_user.requests.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.text { render 'show.html',layout: false }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = current_user.requests.new
  
    @request.comment = params[:comment] if !params[:comment].nil?
    @request.type = params[:type]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = current_user.requests.find(params[:id])
    
    respond_to do |format|
      
      format.html 
      format.text { render 'edit.text',:layout=>false }
    end
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = current_user.requests.new
    @request.type = params[:request][:type]
    @request.start_date = params[:request][:start_date]
    @request.end_date = params[:request][:end_date]
    @request.comment = params[:request][:comment]
    @request.status = "Pending"
    @request.organization_id = current_user.organization.id

    respond_to do |format|
      if @request.save
        format.html { redirect_to requests_url, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = current_user.requests.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to requests_url, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = current_user.requests.find(params[:id])
    @request.status = "Cancelled"
    @request.save

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
    
  def cancellation
    @request = current_user.requests.find(params[:request_id])
    
    respond_to do |format|  
      format.html 
      format.text { render 'cancellation.text',:layout=>false }
    end
  end
  
  def cancel
    @request = current_user.requests.find(params[:request_id])
    if params[:request][:cancel] == "1"
      @request.status = "Cancelled"
      @request.save
      redirect_to requests_path, notice: 'Request is successfully cancelled.'
    else
      redirect_to requests_path, notice: 'Error in cancelling request'
    end
  end
  
    def approving
    @request = Request.find(params[:request_id])
    
    respond_to do |format|  
      format.html 
      format.text { render 'approving.text',:layout=>false }
    end
  end
  
  def approve
    @request = Request.find(params[:request_id])
    if params[:request][:approve] == "2"
      @request.status = "Approved"
      @request.save
      if @request.type == "Annual"
        @info = @request.user.leave_infos.where(:leave_type => "Annual Leave").all.first
        @info.remaining_leave = @info.remaining_leave - (@request.end_date.to_date - @request.start_date.to_date)
        @info.save
      elsif @request.type == "Medical"
        @info = @request.user.leave_infos.where(:leave_type => "Medical Leave").all.first
        @info.remaining_leave = @info.remaining_leave - (@request.end_date.to_date - @request.start_date.to_date)
        @info.save
      end
      redirect_to admin_index_path, notice: 'Request is successfully approved.'
    else
      redirect_to admin_index_path, notice: 'Request approval error'
    end
  end
  
  def rejecting
    @request = Request.find(params[:request_id])
    
    respond_to do |format|  
      format.html 
      format.text { render 'rejecting.text',:layout=>false }
    end
  end
  
  def reject
    @request = Request.find(params[:request_id])
    if params[:request][:reject] == "3"
      @request.status = "Rejected"
      @request.save
      redirect_to admin_index_path, notice: 'Request rejected successfully '
    else
      redirect_to admin_index_path, notice: 'Request rejecting error'
    end
  end
  
end

app/views/requests/_approve.html.erb
Are you sure?
<%= simple_form_for(@request,:url => request_approve_path(@request), :html => { :class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :approve, :value => 2%>
  
  <div class="form-actions">
    <%= f.submit "Yes", :class => "btn-primary"%>
    <a class="btn" data-dismiss="modal" href="#">Cancel</a>
  </div>
<% end %>

app/views/requests/_cancel.html.erb
Are you sure?
<%= simple_form_for(@request,:url => request_cancel_path(@request), :html => { :class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :cancel, :value => 1%>
  
  <div class="form-actions">
    <%= f.submit "Yes", :class => "btn-primary"%>
    <a class="btn" data-dismiss="modal" href="#">Cancel</a>
  </div>
<% end %>

app/views/requests/_form.html.erb
<%= simple_form_for(@request, :html => { :class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :start_date, :input_html => { :class => "datepickers" } %>
  <%= f.input :end_date, :input_html => { :class => "datepickers" } %>
  <%= f.input :type, :collection => ["Annual","Medical","Overtime"], :selected => ["Annual"] %>
  <%= f.input :comment %>
   
  <div class="form-actions">
    <%= f.submit "Submit", :class => "btn-primary"%>
    <%= link_to 'Back', requests_path, :class => "btn" %>
  </div>
<% end %>

app/views/requests/_reject.html.erb
Are you sure?
<%= simple_form_for(@request,:url => request_reject_path(@request), :html => { :class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :reject, :value => 3%>
  
  <div class="form-actions">
    <%= f.submit "Yes", :class => "btn-primary"%>
    <a class="btn" data-dismiss="modal" href="#">Cancel</a>
  </div>
<% end %>

app/views/requests/approving.html.erb
<%= render 'approve' %>

app/views/requests/approving.text.erb
<%= render 'approve.html',:format=> :html %>

app/views/requests/cancellation.html.erb
<h1>Editing request</h1>

<%= render 'cancel' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/cancellation.text.erb
<%= render 'cancel.html',:format=> :html %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/edit.text.erb
<%= render 'form.html',:format=> :html %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table class = "table table-striped">
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Type</th>
    <th>Comment</th>
    <th>Status</th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  
  <tr>
    <td><%= request.start_date.to_date %></td>
    <td><%= request.end_date.to_date %></td>
    <td><%= request.type %></td>
    <td><%= request.comment %></td>
    <td><%= request.status %></td>
    
    <td><%= modal_me_to 'Cancel', request_cancellation_path(request), {:class=>'btn btn-danger'}, "Cancel My Request" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path, :class => "btn btn-primary" %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

app/views/requests/rejecting.html.erb
<%= render 'reject' %>

app/views/requests/rejecting.text.erb
<%= render 'reject.html',:format=> :html %>