config/routes.rb
LeaveCalendar::Application.routes.draw do

  resources :organizations
  resources :leave_infos
  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  
  match "account" => "account#index"
  resources :requests do
    get "cancellation"
    put "cancel"
    get "approving"
    put "approve"
    get "rejecting"
    put "reject"
  end

  match "admin", to: "admin#index"
  namespace :admin do
    resources :users
  end
    
  match '', to: 'welcome#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  

   root :to => 'welcome#index'
   

end

app/models/leave_info.rb
class LeaveInfo
  include Mongoid::Document
  field :leave_type, :type => String
  field :granted_leave, :type => Integer
  field :remaining_leave, :type => Integer
  embedded_in :user
end

app/controllers/leave_infos_controller.rb
class LeaveInfosController < ApplicationController
  before_filter :load_organization


  # GET /leave_infos
  # GET /leave_infos.json
  def index
    @leave_infos = current_user.leave_infos.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leave_infos }
    end
  end

  # GET /leave_infos/1
  # GET /leave_infos/1.json
  def show
    @leave_info = current_user.leave_infos.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leave_info }
    end
  end

  # GET /leave_infos/new
  # GET /leave_infos/new.json
  def new
    @leave_info = current_user.leave_infos.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leave_info }
    end
  end

  # GET /leave_infos/1/edit
  def edit
    @leave_info = current_user.leave_infos.find(params[:id])
  end

  # POST /leave_infos
  # POST /leave_infos.json
  def create
    @leave_info = current_user.leave_infos.new(params[:leave_info])

    respond_to do |format|
      if @leave_info.save
        format.html { redirect_to @leave_info, notice: 'Leave info was successfully created.' }
        format.json { render json: @leave_info, status: :created, location: @leave_info }
      else
        format.html { render action: "new" }
        format.json { render json: @leave_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leave_infos/1
  # PUT /leave_infos/1.json
  def update
    @leave_info = current_user.leave_infos.find(params[:id])

    respond_to do |format|
      if @leave_info.update_attributes(params[:leave_info])
        format.html { redirect_to @leave_info, notice: 'Leave info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leave_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leave_infos/1
  # DELETE /leave_infos/1.json
  def destroy
    @leave_info = LeaveInfo.find(params[:id])
    @leave_info.destroy

    respond_to do |format|
      format.html { redirect_to leave_infos_url }
      format.json { head :no_content }
    end
  end
end

app/views/leave_infos/_form.html.erb
<%= simple_form_for(@leave_info, :html => { :class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :leave_type %>
  <%= f.input :granted_leave %>
  <%= f.input :remaining_leave %>

  <div class="form-actions">
    <%= f.submit "Submit", :class => "btn-primary"%>
    <%= link_to 'Back', leave_infos_path, :class => "btn" %>
  </div>
<% end %>

app/views/leave_infos/edit.html.erb
<h1>Editing leave_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @leave_info %> |
<%= link_to 'Back', leave_infos_path %>

app/views/leave_infos/index.html.erb
<h1>Your leave informations</h1>

<table class="table table-striped">
  <tr>
    <th>Leave type</th>
    <th>Granted leave</th>
    <th>Remaining leave</th>
  </tr>

<% @leave_infos.each do |leave_info| %>
  <tr>
    <td><%= leave_info.leave_type %></td>
    <td><%= leave_info.granted_leave %></td>
    <td><%= leave_info.remaining_leave %></td>
  </tr>
<% end %>
</table>

app/views/leave_infos/new.html.erb
<h1>New leave_info</h1>

<%= render 'form' %>

app/views/leave_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Leave type:</b>
  <%= @leave_info.leave_type %>
</p>

<p>
  <b>Granted leave:</b>
  <%= @leave_info.granted_leave %>
</p>

<p>
  <b>Remaining leave:</b>
  <%= @leave_info.remaining_leave %>
</p>


<%= link_to 'Edit', edit_leave_info_path(@leave_info) %> |
<%= link_to 'Back', leave_infos_path %>