config/routes.rb
LeaveCalendar::Application.routes.draw do

  resources :organizations
  resources :leave_infos
  devise_for :users, :controllers => { :sessions => "admin/sessions" }
  
  match "account" => "account#index"
  resources :requests do
    get "cancellation"
    put "cancel"
    get "approving"
    put "approve"
    get "rejecting"
    put "reject"
  end

  match "admin", to: "admin#index"
  namespace :admin do
    resources :users
  end
    
  match '', to: 'welcome#index', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  

   root :to => 'welcome#index'
   

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= javascript_include_tag "application" %>
    <meta charset="utf-8">
    <title>LeaveCalendar</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <%= link_to "Leave Calendar", root_path, :class => "brand"%>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
                <li>  
                  <% if user_signed_in? %>
                    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                    <li><%= link_to current_user.name, account_path %></li>
                  <% else %>
                    <%= link_to "Sign up", new_user_registration_path %>
                    <li><%= link_to "Sign in", new_user_session_path %></li>
                  <% end %>
                </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
              <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                 <ul class="nav nav-list">
                    <li class="nav-header">Sidebar</li>
                    <%if current_user != nil%>
                      <li><%= link_to "My Requests", requests_path  %></li>
                      <li><%= link_to "My Leave Info", leave_infos_path  %></li>
                      <li><%= link_to "My Organization", organizations_path if current_user.authority_level = "Admin"%></li>
                    <%end%>
                </ul>
              </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy; Welcome <%= @organization.name if !@organization.nil?%> Organization</p>
      </footer>

    </div> <!-- /container -->
    <%= render 'shared/modal_me'%>

  </body>
</html>